0:
  name : leftDown
  side : left
1:
  name : leftUp
  side : left
2:
  name : rightDown
  side : right
3:
  name : rightUp
  side : right
4:
  name : twoDown
  side : both
5:
  name : twoUp
  side : both
6:
  name : heart
  side : both
7:
  name : normal
  side : both